version: '3'
services:
  jenkins:
    build: .
    container_name: jenkins_ansible
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-data:/var/jenkins_home
      # - /maven_project:/var/jenkins_home/workspace/maven_project

  web_server:
    image: nginx
    container_name: web_server
    ports:
      - "80:80"
    volumes:
      - web_server_data:/usr/share/nginx/html

volumes:
  jenkins-data:
  web_server_data:
